# Generated by Django 5.2.4 on 2025-05-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Unknown article', max_length=100)),
                ('Photo', models.ImageField(blank=True, default='None', upload_to='')),
                ('Source', models.CharField(default='', max_length=100)),
                ('Sub_Title', models.CharField(default='', max_length=100)),
                ('Content', models.TextField(default='')),
                ('Category', models.CharField(choices=[('POLITICS', 'Politics'), ('TECHNOLOGY', 'Technology'), ('SPORT', 'Sport'), ('ART', 'Art')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
