# Generated by Django 5.2.1 on 2025-09-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Photo',
        ),
    ]
