# Generated by Django 5.2.1 on 2025-10-19 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
