# Generated by Django 5.2.1 on 2025-10-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Slug',
            field=models.SlugField(blank=True, default='news', max_length=100, null=True, unique=True),
        ),
    ]
