# Generated by Django 5.2.1 on 2025-10-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Slug',
        ),
    ]
